In [1]:
import petthermotools as ptt 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

#### uncomment these two lines if alphaMELTS files are not added to your Python path - obviously you're have to change the file location
# import sys
# sys.path.append(r"/Users/gleesonm/Library/CloudStorage/GoogleDrive-gleesonm@berkeley.edu/My Drive/2022/GitHub/MELTS130beta/MacOS")

alphaMELTS for Python files successfully located.
If using the Green et al. (2025) or Weller et al. (2024) thermodynamic models please run `ptt.activate_petthermotools_env()` prior to any calculations.

In [2]:
bulk = {'SiO2': 53.93,
        'TiO2': 0.67,
        'Al2O3': 18.56,
        'FeOt': 8.5,
        'MnO': 0.21,
        'MgO': 3.96,
        'CaO': 9.16,
        'Na2O': 2.92,
        'K2O': 0.69,
        'P2O5': 0.13}

In [3]:
Combined = ptt.equilibrate_multi(Model = "MELTSv1.2.0", bulk = bulk, T_C = np.zeros(100) + 1070, # small bug, you have to make sure T_C is the correct size
                      P_bar = 2000, H2O_init = np.random.random(100)*10,
                      fO2_buffer="NNO", fO2_offset = 1)

Completed 4.0 %
Completed 8.0 %
Completed 12.0 %
Completed 16.0 %
Completed 20.0 %
Completed 24.0 %
Completed 28.0 %
Completed 32.0 %
Completed 36.0 %
Completed 40.0 %
Completed 44.0 %
Completed 48.0 %
Completed 52.0 %
Completed 56.0 %
Completed 60.0 %
Completed 64.0 %
Completed 68.0 %
Completed 72.0 %
Completed 76.0 %
Completed 80.0 %
Completed 84.0 %
Completed 88.0 %
Completed 92.0 %
Completed 96.0 %
Completed 100.0 %

In [4]:
Combined['liquid1']

,SiO2_Liq,TiO2_Liq,Al2O3_Liq,Cr2O3_Liq,Fe2O3_Liq,FeO_Liq,FeOt_Liq,MnO_Liq,MgO_Liq,CaO_Liq,Na2O_Liq,K2O_Liq,P2O5_Liq,H2O_Liq,CO2_Liq,Fe3Fet_Liq
0,54.213788,0.527309,18.117105,0.0,1.642242,3.838027,5.315706,0.211105,3.643242,9.208201,2.935365,0.693631,0.130684,4.839299,0.0,0.277984
1,53.835613,0.516817,18.002623,0.0,1.630795,3.827442,5.294821,0.209632,3.621241,9.143968,2.914889,0.688792,0.129772,5.478412,0.0,0.277135
2,53.964240,0.520401,18.041785,0.0,1.634815,3.831435,5.302431,0.210133,3.628826,9.165816,2.921854,0.690438,0.130083,5.260174,0.0,0.277419
3,53.835613,0.516817,18.002623,0.0,1.630795,3.827442,5.294821,0.209632,3.621241,9.143968,2.914889,0.688792,0.129772,5.478412,0.0,0.277135
4,53.938218,0.519677,18.033880,0.0,1.634012,3.830658,5.300932,0.210032,3.627300,9.161396,2.920445,0.690105,0.130020,5.304257,0.0,0.277361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,53.835613,0.516817,18.002623,0.0,1.630795,3.827442,5.294821,0.209632,3.621241,9.143968,2.914889,0.688792,0.129772,5.478412,0.0,0.277135
96,53.835613,0.516817,18.002623,0.0,1.630795,3.827442,5.294821,0.209632,3.621241,9.143968,2.914889,0.688792,0.129772,5.478412,0.0,0.277135
97,53.835613,0.516817,18.002623,0.0,1.630795,3.827442,5.294821,0.209632,3.621241,9.143968,2.914889,0.688792,0.129772,5.478412,0.0,0.277135
98,54.787452,0.541250,18.115956,0.0,1.659991,3.858517,5.352165,0.215098,3.703761,9.214051,2.975507,0.706330,0.133156,4.088932,0.0,0.279074
99,66.324667,1.119588,12.883065,0.0,1.605226,3.750632,5.195004,0.701241,1.999700,6.557989,2.257111,1.742048,0.434102,0.624633,0.0,0.278031

## Run the same calculation but suppress ALL solids (random H2O and CO2 contents)

In [5]:
NoSolids = ptt.equilibrate_multi(Model = "MELTSv1.2.0", bulk = bulk, T_C = np.zeros(100) + 1070, P_bar = 500, H2O_init = np.random.random(100)*10, 
                                 CO2_init = np.random.random(100)*0.4, fO2_buffer = "NNO", fO2_offset = 1, Suppress = "All")

Completed 4.0 %
Completed 8.0 %
Completed 12.0 %
Completed 16.0 %
Completed 20.0 %
Completed 24.0 %
Completed 28.0 %
Completed 32.0 %
Completed 36.0 %
Completed 40.0 %
Completed 44.0 %
Completed 48.0 %
Completed 52.0 %
Completed 56.0 %
Completed 60.0 %
Completed 64.0 %
Completed 68.0 %
Completed 72.0 %
Completed 76.0 %
Completed 80.0 %
Completed 84.0 %
Completed 88.0 %
Completed 92.0 %
Completed 96.0 %
Completed 100.0 %

In [6]:
NoSolids['All'].head()

,T_C,P_bar,mass_g,H_J,S_J/K,V_cm^3,rho_kg/m^3,log10(fO2),dVdP_cm^3/bar,mass_g_Liq,...,Na2O_Liq,K2O_Liq,P2O5_Liq,H2O_Liq,CO2_Liq,Fe3Fet_Liq,H2O_Fl,CO2_Fl,X_H2O_mol_Fl,X_CO2_mol_Fl
0,1070.0,500.0,100.244460,-1.250244e+06,334.158707,131.100795,764.636554,-8.200846,0.082121,92.427691,...,2.885115,0.681757,0.128447,2.184718,0.000321,0.282834,97.238003,2.761997,0.988513,0.011487
1,1070.0,500.0,100.257199,-1.256929e+06,296.283258,75.074904,1335.428929,-8.200846,0.031190,97.225018,...,2.885539,0.681857,0.128466,2.170060,0.000588,0.282848,95.009126,4.990874,0.978962,0.021038
2,1070.0,500.0,100.246578,-1.251977e+06,328.570579,122.686693,817.094142,-8.200846,0.074668,93.246341,...,2.884695,0.681657,0.128428,2.199239,0.000056,0.282821,99.512278,0.487722,0.997999,0.002001
3,1070.0,500.0,100.258320,-1.257296e+06,292.721538,70.011093,1432.034775,-8.200846,0.026531,97.624289,...,2.886082,0.681985,0.128490,2.151279,0.000929,0.282866,92.246695,7.753305,0.966759,0.033241
4,1070.0,500.0,100.267180,-1.261893e+06,268.330005,40.519711,2474.528519,-8.200846,0.000382,100.163932,...,2.903515,0.686105,0.129266,1.549702,0.010930,0.283437,37.412263,62.587737,0.593691,0.406309

# Run an equilibrate calculation using the Green et al. (2025) thermodynamic model via MAGEMin

In [7]:
Eq_Green = ptt.equilibrate_multi(Model = "Green2025", bulk = bulk, 
                                 T_C = np.zeros(100) + 1070.0, 
                                 P_bar = 500.0, H2O_init = np.random.random(100)*10.0, 
                                 Fe3Fet_init = 0.15)

Julia environment detected.
Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

  Activating project at `~/.petthermotools_julia_env`

Using libMAGEMin.dylib from MAGEMin_jll

Computing 100 points... 100%|████████████████████████████| Time: 0:00:06

In [8]:
Eq_Green['All']

,T_C,P_bar,mass_g,H_J,S_J/K,V_cm^3,rho_kg/m^3,log10(fO2),mass_per_mole_g/mol,eta_Pa.s,...,TiO2_Opx,Al2O3_Opx,Cr2O3_Opx,FeOt_Opx,MgO_Opx,CaO_Opx,Na2O_Opx,K2O_Opx,H2O_Opx,Fe3Fet_Opx
0,1070.0,500.0,100.0,-1.283543e+06,257.957448,52.419107,1907.701332,-9.786312,60.560050,177.892958,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1070.0,500.0,100.0,-1.276016e+06,298.435621,111.844467,894.098765,-9.846571,54.172499,183.951062,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1070.0,500.0,100.0,-1.276268e+06,297.058529,109.818200,910.595879,-9.843012,54.368143,183.442593,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1070.0,500.0,100.0,-1.276190e+06,297.486343,110.447328,905.408953,-9.846352,54.307179,183.676441,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1070.0,500.0,100.0,-1.285313e+06,247.973672,39.191742,2551.557955,-9.780237,62.386696,199.279851,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1070.0,500.0,100.0,-1.274501e+06,306.551570,123.724323,808.248513,-9.859548,53.050925,184.735321,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,1070.0,500.0,100.0,-1.286464e+06,243.065575,38.471434,2599.331226,-9.656885,63.252816,440.889858,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,1070.0,500.0,100.0,-1.283579e+06,257.774373,52.151756,1917.480985,-9.787059,60.592131,177.933433,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,1070.0,500.0,100.0,-1.282114e+06,265.666385,63.760838,1568.360819,-9.796866,59.229561,179.318088,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,1070.0,500.0,100.0,-1.277736e+06,289.204654,98.316845,1017.119697,-9.830117,55.507453,182.745753,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
Eq_Green['PhaseList']

0     Plag,Liq,Fl
1     Plag,Liq,Fl
2     Plag,Liq,Fl
3     Plag,Liq,Fl
4        Plag,Liq
         ...
95    Plag,Liq,Fl
96    Plag,Ol,Liq
97    Plag,Liq,Fl
98    Plag,Liq,Fl
99    Plag,Liq,Fl
Length: 100, dtype: str